In [2]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
conn = sqlite3.connect('../data/chinook.db')  # Update with your database path

In [4]:
cursor = conn.cursor()

In [5]:
cursor.execute("""
      SELECT name FROM sqlite_master WHERE type='table';         
               """)
cursor.fetchall()

[('Album',),
 ('Artist',),
 ('Customer',),
 ('Employee',),
 ('Genre',),
 ('Invoice',),
 ('InvoiceLine',),
 ('MediaType',),
 ('Playlist',),
 ('PlaylistTrack',),
 ('Track',)]

In [7]:
#Which are the 10 best-selling tracks?

top_tracks = pd.read_sql_query("""
SELECT 
    t.Name AS Track,
    SUM(il.Quantity) AS TotalSold
FROM InvoiceLine il
JOIN Track t 
ON il.TrackId = t.TrackId
GROUP BY t.Name
ORDER BY TotalSold DESC
LIMIT 10;
""", conn)  

top_tracks

                       Track  TotalSold
0                The Trooper          5
1                   Untitled          4
2    The Number Of The Beast          4
3        Sure Know Something          4
4       Hallowed Be Thy Name          4
5                   Eruption          4
6          Where Eagles Dare          3
7  Welcome Home (Sanitarium)          3
8             Sweetest Thing          3
9                  Surrender          3

In [ ]:
#Which country generates the most revenue?

country_sales = pd.read_sql_query("""
SELECT 
    c.Country,
    ROUND(SUM(i.Total), 2) AS Revenue
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.Country
ORDER BY Revenue DESC;
""", conn)  

country_sales

           Country  Revenue
0              USA   523.06
1           Canada   303.96
2           France   195.10
3           Brazil   190.10
4          Germany   156.48
5   United Kingdom   112.86
6   Czech Republic    90.24
7         Portugal    77.24
8            India    75.26
9            Chile    46.62
10         Ireland    45.62
11         Hungary    45.62
12         Austria    42.62
13         Finland    41.62
14     Netherlands    40.62
15          Norway    39.62
16          Sweden    38.62
17           Spain    37.62
18          Poland    37.62
19           Italy    37.62
20         Denmark    37.62
21         Belgium    37.62
22       Australia    37.62
23       Argentina    37.62

In [ ]:
# Who is the top-performing sales employee?

top_employee = pd.read_sql_query("""
SELECT 
    e.FirstName || ' ' || e.LastName AS Employee,
    ROUND(SUM(i.Total), 2) AS Revenue
FROM Employee e
JOIN Customer c
ON e.EmployeeId = c.SupportRepId
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY Employee
ORDER BY Revenue DESC;  
""", conn)

top_employee

        Employee  Revenue
0   Jane Peacock   833.04
1  Margaret Park   775.40
2  Steve Johnson   720.16

In [11]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)
print("Database Tables:\n", tables )

Database Tables:
              name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track